# Site settings
title: Brandon Minor
name: Thinking Fast | Typing Slow
email: gallimatrix@gmail.com
description: "or, Brandon Minor is on his computer most of the time."
url: "http://bminortx.github.io"
twitter_username: bminortx
github_username:  bminortx

# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 4
excerpt_separator: <!--more-->