# Site settings
title: B. Minor Thinks Fast & Types Slow
name: Brandon Minor
email: gallimatrix~at~gmail.com
description: "In which I wildly pontificate and flail my arms around."
url: "http://bminortx.github.io"
twitter_username: bminortx
github_username:  bminortx
gems: 
  - jekyll-paginate
  - jekyll-feed

# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 4
excerpt_separator: <!--more-->
