# Site settings
title: B. Minor Thinks Fast & Types Slow
name: Brandon Minor
email: gallimatrix@gmail.com
description: "In which I explain things within my areas of expertise, in addition to some that aren't."
url: "http://bminortx.github.io"
twitter_username: bminortx
github_username:  bminortx
gems: 
  - jekyll-paginate
  - jekyll-feed

# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 4
excerpt_separator: <!--more-->
